Implementations of the activation functions

In [2]:
import numpy as np

In [3]:
def step_function(x):
    """
    Implements the step function

    Args:
        x (np.ndarray): Input Numpy array.
    Returns:
       np.ndarray: A Numpy array of the same shape as x, 
                    containing 1 for positive elements and 0 otherwise.
    """
    y = x >0
    return y.astype(int)

In [4]:
#Input Example
x = np.array([-1.0, 1.0, 2.0])
step_function(x)

array([0, 1, 1])

In [5]:
# Implements the Sigmoid fuction
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
#Input Example
x = np.array([-1.0,1.0,2.0])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

In [7]:
# Implements the ReLu function
def relu(x):
    return np.maximum(0, x)

In [8]:
#Input Example
x = np.array([-1.0,1.0,2.0])
relu(x)

array([0., 1., 2.])

In [9]:
def identity_fuction(x):
    return x

In [28]:
#Implements the Softmax function
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c) #For preventing overflow
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

Example) An implementation of 3-layer neural network

In [11]:
def init_network():
    # Set arbitrary weights
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4], [0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])

    return network

def forward(network,x):
    # Perform the forward propagation
    W1, W2, W3 = network['W1'],network['W2'],network['W3']
    b1, b2, b3 = network['b1'],network['b2'],network['b3']

    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3
    z3 = sigmoid(a3) 

    y = identity_fuction(a3)

    return y

In [12]:
network = init_network()
x = np.array([1.0,0.5])
y = forward(network,x)
y

array([0.31682708, 0.69627909])

Example) An implementation of the inference process using the MNIST dataset

In [24]:
from mnist import load_mnist
import pickle
def get_data():
    # Get data from the mnist dataset
    (x_train, t_train), (x_test,t_test) = load_mnist(flatten = True, normalize = False)

    return x_test, t_test

def init_network():
    # load the pre-trained sample weights
    with open("sample_weight.pkl", "rb") as f:   
        network = pickle.load(f)

    return network

def predict(network, x):
    # Perform forward propagation and return prediction
    W1,W2,W3 = network['W1'],network['W2'],network['W3']
    b1,b2,b3 = network['b1'],network['b2'],network['b3']

    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3
    y = softmax(a3)

    return y

In [29]:
x, t = get_data()
network = init_network()

batch_size = 100
accuracy_cnt = 0

for i in range(0,len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])

print(float(accuracy_cnt/len(x)))

0.9207


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_13472\3386560700.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
