In [1]:
import numpy as np 

Implementations of the functions for neural network training

In [ ]:
# Implements the sum squares error
def sum_squares_error(y,t):
    return 0.5*np.sum((y-t)**2)

In [ ]:
# Implements the cross entropy error for one-hot encoding
def cross_entropy_error(y,t):
    delta = 1e-7
    return -np.sum(t*np.log(y+delta))

In [ ]:
# Implements the cross entropy error for batch and non-one-hot encoding
def cross_entropy_error(y,t):
    delta = 1e-7
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]

    return -np.sum(np.log(y[np.arange(batch_size),t] + delta)) / batch_size
    

In [ ]:
# Implements numerical differentiation 
def numerical_diff(f,x):
    h = 1e-4
    return (f(x+h)-f(x-h))/2*h

In [ ]:
# Example usage of numerical_diff
def function_1(x):
    return 0.01*x**2 + 0.1*x

numerical_diff(function_1,5)

1.9999999999908982e-09

In [ ]:
# Implements numerical gradient 
def numerical_gradient(f,x):
    h = 1e-4
    grad = np.zeros_like(x)

    for idx in range(x.size):
        tmp_val = x[idx]

        # Calculates f(x+h)
        x[idx] = tmp_val + h
        fxh1 = f(x)

        # Calculates f(x-h)
        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1-fxh2) / (2*h)
        # Restores the value
        x[idx] = tmp_val 
    
    return grad

In [ ]:
# Example usage of numerical_gradient
def function_2(x):
    return x[0]**2 + x[1]**2

numerical_gradient(function_2, np.array([3.0,4.0]))

array([6., 8.])

In [ ]:
# Implements gradient descent
def gradient_descent(f, init_x, lr=0.01, step_num = 100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f,x)
        x -= lr*grad
    return x

In [18]:
# Example usage of gradient_descent
init_x = np.array([-3.0,4.0])
gradient_descent(function_2, init_x,lr=0.1,step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

Example) An implementation of training for a simple neural network

In [23]:
from functions import softmax, cross_entropy_error

class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [24]:
net = simpleNet()

x = np.array([0.6,0.9])
p = net.predict(x)
print(p, np.argmax(p))

t = np.array([0,0,1])
print(net.loss(x,t))


[-1.18278706  0.97702534  0.66264688] 1
0.9271768717326897
